apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbuilder-keycloak-service
  labels:
    app: appbuilder-keycloak-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appbuilder-keycloak-service
  template:
    metadata:
      labels:
        app: appbuilder-keycloak-service
    spec:
      containers:
      - name: appbuilder-keycloak-service
        image: oumaima12/keycloak-service:22.0.1
        ports:
        - containerPort: 8080
        env: 
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin


---
apiVersion: v1
kind: Service
metadata:
  name: appbuilder-keycloak-service-service
spec:
  selector:
    app: appbuilder-keycloak-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
