apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-builder-frontend
  labels:
    app: app-builder-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-builder-frontend
  template:
    metadata:
      labels:
        app: app-builder-frontend
    spec:
      containers:
      - name: app-builder-frontend
        image: oumaima12/app-builder-frontend
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: appbuilder-frontend-service
spec:
  selector:
    app: app-builder-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
