apiVersion: apps/v1
kind: Deployment
metadata:
  name: appbuilder-screen-service
  labels:
    app: appbuilder-screen-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appbuilder-screen-service
  template:
    metadata:
      labels:
        app: appbuilder-screen-service
    spec:
      containers:
      - name: appbuilder-screen-service
        image: oumaima12/screen-service:V5
        ports:
        - containerPort: 9882
---
apiVersion: v1
kind: Service
metadata:
  name: appbuilder-screen-service-service
spec:
  selector:
    app: appbuilder-screen-service
  ports:
  - protocol: TCP
    port: 9882
    targetPort: 9882
